development: &default
  adapter: postgresql
  database: trial_development
  encoding: utf8
  min_messages: warning
  pool: 5
  timeout: 5000
  host: localhost
  port: 5432
  username: trial
  password: trial

test:
  <<: *default
  database: trial_test

production:
  <<: *default
  database: trial_production 

staging:
  <<: *default
  database: trial_staging   